[package]
name = "s3_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
actix-web = "4.9.0"
rust-s3 = { version = "0.35.1", features = ["tokio"] }