name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .

    # Step 4: Push the Docker image to GitHub Container Registry
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
